name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code
      - name: Run setup gtk
        run: sudo apt-get install libgtk-3-dev
      - name: Build application
        run: make
      - name: Build test
        run: make test
      - name: Run test
        run: ./bin/test/unit_converter_test 
